package org.calebe.quarkus.panache.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.math.BigDecimal;

import org.calebe.quarkus.panache.model.CD;
import org.junit.jupiter.api.Test;

import io.quarkus.test.TestTransaction;
import io.quarkus.test.junit.QuarkusTest;



@QuarkusTest
public class CDRepositoryTest {


    @Test
    @TestTransaction
    public void shouldCreateAndFindCD() {

        long count = CD.count();
        int listAllSize =  CD.listAll().size();
        assertEquals(count, listAllSize);//Check if the sizes match


        //Creating and setting a cd object
        CD cd = new CD();
        cd.title = "Wonderful cd";
        cd.price = BigDecimal.valueOf(10);
        
        //Persisting a cd
        CD.persist(cd);
        assertNotNull(cd.id);//The id is autogenerated cause it extends PanacheEntity

        assertEquals(count + 1, CD.count());//Adicionou um cd, veja se adicionou no bd

        CD.findById(cd.id);//Find the cd
        assertEquals("Wonderful cd", cd.title);

        CD.deleteById(cd.id);//Deletado :)
        assertEquals(count, CD.count());//It must return to the initial count
    }

}