package org.calebe.quarkus.panache.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.time.Duration;

import org.calebe.quarkus.panache.model.Track;
import org.junit.jupiter.api.Test;

import io.quarkus.test.TestTransaction;
import io.quarkus.test.junit.QuarkusTest;



@QuarkusTest
public class TrackRepositoryTest {


    @Test
    @TestTransaction
    public void shouldCreateAndFindTrack() {

        long count = Track.count();
        int listAllSize =  Track.listAll().size();
        assertEquals(count, listAllSize);//Check if the sizes match


        //Creating and setting a track object
        Track track = new Track();
        track.title = "Awesome music";
        track.duration = Duration.ofSeconds(1000);
        
        //Persisting a track
        Track.persist(track);
        assertNotNull(track.id);//The id is autogenerated cause it extends PanacheEntity

        assertEquals(count + 1, Track.count());//Adicionou uma track, veja se adicionou no bd

        Track.findById(track.id);//Find the track
        assertEquals("Awesome music", track.title);

        Track.deleteById(track.id);//Deletado :)
        assertEquals(count, Track.count());//It must return to the initial count
    }

}